version: "3.8"

services:
  backend:
    env_file:
      - .env
    build:
      context: ./server
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data/
  frontend:
    build:
      context: ./client
    volumes:
      - frontend:/app/build
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - frontend:/var/www/client
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - backend
      - frontend
    env_file:
      - .env

volumes:
  frontend:
  db_volume:
