version: "3.8"

services:
  backend:
    build:
      context: ./server
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data/
  frontend:
    build:
      context: ./client
      args:
        REACT_APP_API_URL: "${REACT_APP_API_URL}"
    volumes:
      - frontend:/app/build
    ports:
      - "${NGINX_PORT}:80"
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  frontend:
  db_volume:
