version: "3.8"

services:
  backend:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: ./server
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db-library
      - DATABASE_URL='postgres://postgres:postgres@db:5433/db-library'
    ports:
      - "5433:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data/
  frontend:
    build:
      context: ./client
    volumes:
      - frontend:/app/build
  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/client
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  static:
  frontend:
  db_volume:
