# Generated by Django 4.2.1 on 2023-06-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='books_onloan',
            field=models.ManyToManyField(blank=True, to='book.bookinstance'),
        ),
    ]
