# Generated by Django 4.2.1 on 2023-12-13 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_books_onloan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="books_onloan",
        ),
    ]
