# Generated by Django 4.2.1 on 2023-06-06 23:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('series', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('edition', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('book_image', models.CharField(blank=True, max_length=1000, null=True)),
                ('book_format', models.CharField(blank=True, choices=[('p', 'Paperback'), ('m', 'Mass Market Paperback'), ('k', 'Kindle edition'), ('e', 'Ebook'), ('h', 'Hardcover')], help_text='Book availability', max_length=1, null=True)),
                ('author', models.ManyToManyField(help_text='Select an author for this book', to='book.author')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the book', primary_key=True, serialize=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('l', 'On loan'), ('f', 'Free'), ('r', 'Reserved')], default='f', help_text='Book availability', max_length=1, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='book.book')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='book.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.language'),
        ),
    ]
